import type { Metadata } from "next";
import "@/app/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import localFont from "next/font/local";

import { getCommon } from "@/lib/cms/common";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ptserif = localFont({
    variable: '--font-ptserif',
    src: [
        {
            path: '../public/static/fonts/PTSerif-Regular.woff2',
            weight: '400',
            style: 'normal',
        },
    ],
});


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // common for navbar and footer
  const common = await getCommon();

  return (
    <html lang="en">
      <body className={`${ptserif.variable} bg-gray-300`}>
        <Navbar common={common}/>
        {children}
        <Footer common={common} />
      </body>
    </html>
  );
}
