import type { Metadata } from "next";
import "@/app/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import localFont from "next/font/local";

import { getCommon } from "@/lib/cms/common";
import {Common} from "@/lib/types";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ptserif = localFont({
    variable: '--font-ptserif',
    src: [
        {
            path: '../public/static/fonts/PTSerif-Regular.woff2',
            weight: '400',
            style: 'normal',
        },
    ],
});

function normalizeCommon(raw: unknown): Common {
  // Use type assertion and fallback values
  const data = raw as Partial<Common> | undefined;

  return {
    socialMediaCollection: {
      items: data?.socialMediaCollection?.items ?? [],
    },
    navItemsCollection: {
      items: data?.navItemsCollection?.items ?? [],
    },
    nameSurname: data?.nameSurname ?? "",
    footerCopyRight: data?.footerCopyRight ?? "",
  };
}



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // common for navbar and footer
  const rawCommon = await getCommon();
  const common: Common = normalizeCommon(rawCommon);


  return (
    <html lang="en">
    <body className={`${ptserif.variable} bg-gray-300`}>
    <Navbar common={common} />
    {children}
    <Footer common={common} />
    </body>
    </html>
  );
}
